<?php
namespace App\Controller;

use App\Controller\AppController;
use App\Controller\Helpers\HawkFolder;
use Cake\Core\Configure;
use Cake\Event\Event;
use Cake\Filesystem\File;

/**
 * HawkFiles Controller
 *
 * @property \App\Model\Table\HawkFilesTable $HawkFiles
 *
 * @method \App\Model\Entity\HawkFile[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class HawkFilesController extends ApiController
{
    public function initialize()
    {

        Configure::load('file_directories', 'default');
        parent::initialize(); // TODO: Change the autogenerated stub
    }


    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub

        $this->Auth->allow(['inbox', 'outbox', 'types', 'offices', 'download', 'view', 'senders']);
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {
        $hawkFiles = $this->paginate($this->HawkFiles);
        $this->set(compact('hawkFiles'));
    }
    /**
     * @param null $file_id
     *
     **/
    public function view($file_id = null)
    {
        $hawkFile = $this->HawkFiles->get($file_id);
        return $this->getResponse()->withFile($hawkFile->location);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function inboxAdd()
    {
        $hawkFile = $this->HawkFiles->newEntity();
        if ($this->getRequest()->is('post')) {
            $data = $this->getRequest()->getData();
            $hawkFolder = new HawkFolder(Configure::read('production_path') . DS . $data['office']);
            $data['location'] = $hawkFolder->moveToProduction(new File($data['location']['tmp_name']), $data['location']['name']);
            $hawkFile = $this->HawkFiles->patchEntity($hawkFile, $data);
            if ($this->HawkFiles->save($hawkFile)) {
                $this->Flash->success(__('Το αρχείο αποθηκεύτηκε με επιτυχία'));
                return $this->redirect(['action' => 'inbox']);
            }
            $this->Flash->error(__('Δεν καταφέραμε να αποθηκεύσουμε το αρχείο. Παρακαλώ προσπαθήστε ξανά'));
        }
        $this->loadOptions();
        $this->set(compact('hawkFile'));
        $this->render('inboxForm');
    }

    /**
     * Edit method
     *
     * @param string|null $id Hawk File id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function inboxEdit($id = null)
    {
        $hawkFile = $this->HawkFiles->get($id);
        if ($this->getRequest()->is(['patch', 'post', 'put'])) {
            $data = $this->getRequest()->getData();
            $previousFolder = $hawkFile->office;
            $hawkFolder = new HawkFolder(Configure::read('production_path') . DS . $data['office']);
            $hawkFolder->delete($hawkFile->location);
            $data['location'] = $hawkFolder->moveToProduction(new File($data['location']['tmp_name']), $data['location']['name']);
            $hawkFile = $this->HawkFiles->patchEntity($hawkFile, $data);
            if (in_array('office', $hawkFile->getDirty())) {
                $hawkFolder = new HawkFolder(Configure::read('production_path') . DS . $previousFolder);
                $hawkFolder->deleteDir();
            }
            if ($this->HawkFiles->save($hawkFile)) {
                $this->Flash->success(__('Το αρχείο αποθηκεύτηκε με επιτυχία'));
                return $this->redirect(['action' => 'inbox']);
            }
            dd($hawkFile->getErrors());
            $this->Flash->error(__('Δεν καταφέραμε να αποθηκεύσουμε το αρχείο. Παρακαλώ προσπαθήστε ξανά'));
        }
        $this->loadOptions();
        $this->set(compact('hawkFile'));
        $this->render('inboxForm');
    }

    private function loadOptions()
    {
        $types = $this->HawkFiles->find('list', [
            'keyField' => 'type',
            'valueField' => 'type'
        ])->distinct();
        $senders =$this->HawkFiles->find('list', [
            'keyField' => 'sender',
            'valueField' => 'sender'
        ])->distinct();
        $offices =$this->HawkFiles->find('list', [
            'keyField' => 'office',
            'valueField' => 'office'
        ])->distinct();

        $this->set(compact('types', 'senders', 'offices'));

    }

    public function inbox ()
    {
        $files = $this->HawkFiles->find('search', ['search' => $this->getRequest()->getQueryParams()]);

        $this->set(compact('files'));
        $this->set('authUser', $this->Auth->user());
    }

    public function types()
    {
        $types = $this->HawkFiles->find()
            ->select(['type'])
            ->order(['type' => 'ASC'])
            ->distinct()
            ->toArray();

        $this->set('types', $types);
    }
    public function senders()
    {
        $senders = $this->HawkFiles->find()
            ->select(['sender'])
            ->order(['sender' => 'ASC'])
            ->distinct()
            ->toArray();

        $this->set('senders', $senders);
    }
    public function offices()
    {
        $offices = $this->HawkFiles->find()
            ->select(['office'])
            ->order(['office' => 'ASC'])
            ->distinct()
            ->toArray();

        $this->set('offices', $offices);
    }

    public function download($file_id)
    {
        $hawkFile = $this->HawkFiles->get($file_id);
        return $this->getResponse()->withFile($hawkFile->location, [
            'download' => true
        ]);
    }
}
